#ifndef _SCAN_CODES_H_
#define _SCAN_CODES_H_

#pragma pack(push)
#pragma pack(1)
typedef enum _KEYCODE
{

	// Alphanumeric keys ////////////////

	KEY_SPACE = ' ',
	KEY_0 = '0',
	KEY_1 = '1',
	KEY_2 = '2',
	KEY_3 = '3',
	KEY_4 = '4',
	KEY_5 = '5',
	KEY_6 = '6',
	KEY_7 = '7',
	KEY_8 = '8',
	KEY_9 = '9',

	KEY_A = 'a',
	KEY_B = 'b',
	KEY_C = 'c',
	KEY_D = 'd',
	KEY_E = 'e',
	KEY_F = 'f',
	KEY_G = 'g',
	KEY_H = 'h',
	KEY_I = 'i',
	KEY_J = 'j',
	KEY_K = 'k',
	KEY_L = 'l',
	KEY_M = 'm',
	KEY_N = 'n',
	KEY_O = 'o',
	KEY_P = 'p',
	KEY_Q = 'q',
	KEY_R = 'r',
	KEY_S = 's',
	KEY_T = 't',
	KEY_U = 'u',
	KEY_V = 'v',
	KEY_W = 'w',
	KEY_X = 'x',
	KEY_Y = 'y',
	KEY_Z = 'z',

	KEY_RETURN = '\r',
	KEY_ESCAPE = 0x1001,
	KEY_BACKSPACE = '\b',

	// Arrow keys ////////////////////////	E0

	KEY_UP = 0xe048,
	KEY_DOWN = 0xe050,
	KEY_LEFT = 0xe04b,
	KEY_RIGHT = 0xe04d,

	// Function keys /////////////////////

	KEY_F1 = 0x3b,
	KEY_F2 = 0x3c,
	KEY_F3 = 0x3d,
	KEY_F4 = 0x3e,
	KEY_F5 = 0x3f,
	KEY_F6 = 0x40,
	KEY_F7 = 0x41,
	KEY_F8 = 0x42,
	KEY_F9 = 0x43,
	KEY_F10 = 0x44,
	KEY_F11 = 0x57,
	KEY_F12 = 0x58,
	KEY_F13 = 0x59,
	KEY_F14 = 0x5a,
	KEY_F15 = 0x5b,

	KEY_DOT = '.',
	KEY_COMMA = ',',
	KEY_COLON = ':',
	KEY_SEMICOLON = ';',
	KEY_SLASH = '/',
	KEY_BACKSLASH = '\\',
	KEY_PLUS = '+',
	KEY_MINUS = '-',
	KEY_ASTERISK = '*',
	KEY_EXCLAMATION = '!',
	KEY_QUESTION = '?',
	KEY_QUOTEDOUBLE = '\"',
	KEY_QUOTE = '\'',
	KEY_EQUAL = '=',
	KEY_HASH = '#',
	KEY_PERCENT = '%',
	KEY_AMPERSAND = '&',
	KEY_UNDERSCORE = '_',
	KEY_LEFTPARENTHESIS = '(',
	KEY_RIGHTPARENTHESIS = ')',
	KEY_LEFTBRACKET = '[',
	KEY_RIGHTBRACKET = ']',
	KEY_LEFTCURL = '{',
	KEY_RIGHTCURL = '}',
	KEY_DOLLAR = '$',
	KEY_POUND = '�',
	KEY_EURO = '$',
	KEY_LESS = '<',
	KEY_GREATER = '>',
	KEY_BAR = '|',
	KEY_GRAVE = '`',
	KEY_TILDE = '~',
	KEY_AT = '@',
	KEY_CARRET = '^',

	// Numeric keypad //////////////////////

	KEY_KP_0 = '0',
	KEY_KP_1 = '1',
	KEY_KP_2 = '2',
	KEY_KP_3 = '3',
	KEY_KP_4 = '4',
	KEY_KP_5 = '5',
	KEY_KP_6 = '6',
	KEY_KP_7 = '7',
	KEY_KP_8 = '8',
	KEY_KP_9 = '9',
	KEY_KP_PLUS = '+',
	KEY_KP_MINUS = '-',
	KEY_KP_DECIMAL = '.',
	KEY_KP_DIVIDE = '/',
	KEY_KP_ASTERISK = '*',
	KEY_KP_NUMLOCK = 0x45,
	KEY_KP_ENTER = 0x1c,

	KEY_TAB = 0x0f,
	KEY_CAPSLOCK = 0x3a,

	// Modify keys ////////////////////////////

	KEY_LSHIFT = 0x2a,
	KEY_LCTRL = 0x1d,
	KEY_LALT = 0x38,
	KEY_LWIN = 0x4005,
	KEY_RSHIFT = 0x54,
	KEY_RCTRL = 0x4007,
	KEY_RALT = 0x4008,
	KEY_RWIN = 0x4009,

	KEY_INSERT = 0x400a,
	KEY_DELETE = 0xe053,
	KEY_HOME = 0x400c,
	KEY_END = 0x400d,
	KEY_PAGEUP = 0x400e,
	KEY_PAGEDOWN = 0x400f,
	KEY_SCROLLLOCK = 0x4010,
	KEY_PAUSE = 0x4011,

	KEY_UNKNOWN,
	KEY_NUMKEYCODES,

	KEY_SPACE_R = 0xb9,
	KEY_0_R = 0x8b,
	KEY_1_R = 0x82,
	KEY_2_R = 0x83,
	KEY_3_R = 0x84,
	KEY_4_R = 0x85,
	KEY_5_R = 0x86,
	KEY_6_R = 0x87,
	KEY_7_R = 0x88,
	KEY_8_R = 0x89,
	KEY_9_R = 0xa,

	KEY_A_R = 0x9e,
	KEY_B_R = 0xb0,
	KEY_C_R = 0xae,
	KEY_D_R = 0xa0,
	KEY_E_R = 0x92,
	KEY_F_R = 0xa1,
	KEY_G_R = 0xa2,
	KEY_H_R = 0xa3,
	KEY_I_R = 0x97,
	KEY_J_R = 0xa4,
	KEY_K_R = 0xa5,
	KEY_L_R = 0xa6,
	KEY_M_R = 0xb2,
	KEY_N_R = 0xb1,
	KEY_O_R = 0x98,
	KEY_P_R = 0x99,
	KEY_Q_R = 0x90,
	KEY_R_R = 0x93,
	KEY_S_R = 0x9f,
	KEY_T_R = 0x94,
	KEY_U_R = 0x96,
	KEY_V_R = 0xaf,
	KEY_W_R = 0x91,
	KEY_X_R = 0xad,
	KEY_Y_R = 0x95,
	KEY_Z_R = 0xac,

	KEY_RETURN_R = 0x9c,
	KEY_ESCAPE_R = 0x81,
	KEY_BACKSPACE_R = 0x8e,

	// Arrow keys ////////////////////////

	//KEY_UP = 0x1100,
	//KEY_DOWN = 0x1101,
	//KEY_LEFT = 0x1102,
	//KEY_RIGHT = 0x1103,

	// Function keys /////////////////////

	KEY_F1_R = 0xbb,
	KEY_F2_R = 0xbc,
	KEY_F3_R = 0xbd,
	KEY_F4_R = 0xbe,
	KEY_F5_R = 0xbf,
	KEY_F6_R = 0xc0,
	KEY_F7_R = 0xc1,
	KEY_F8_R = 0xc2,
	KEY_F9_R = 0xc3,
	KEY_F10_R = 0xc4,
	KEY_F11_R = 0xd7,
	KEY_F12_R = 0xd8,

	KEY_DOT_R = 0xb4,
	KEY_COMMA_R = 0xb3,
	//KEY_COLON_R = ':',
	KEY_SEMICOLON_R = 0xa7,
	KEY_SLASH_R = 0xb5,
	KEY_BACKSLASH_R = 0xab,
	//KEY_PLUS = '+',
	KEY_MINUS_R = 0x8c,
	//KEY_ASTERISK = '*',
	//KEY_EXCLAMATION = '!',
	//KEY_QUESTION = '?',
	//KEY_QUOTEDOUBLE = '\"',
	KEY_QUOTE_R = 0xa8,
	KEY_EQUAL_R = 0x8d,
	//KEY_HASH = '#',
	//KEY_PERCENT = '%',
	//KEY_AMPERSAND = '&',
	//KEY_UNDERSCORE = '_',
	//KEY_LEFTPARENTHESIS = '(',
	//KEY_RIGHTPARENTHESIS = ')',
	//KEY_LEFTBRACKET = '[',
	//KEY_RIGHTBRACKET = ']',
	//KEY_LEFTCURL = '{',
	//KEY_RIGHTCURL = '}',
	//KEY_DOLLAR = '$',
	//KEY_POUND = '�',
	//KEY_EURO = '$',
	//KEY_LESS = '<',
	//KEY_GREATER = '>',
	//KEY_BAR = '|',
	KEY_GRAVE_R = 0x89,
	/*KEY_TILDE = '~',
	KEY_AT = '@',
	KEY_CARRET = '^',*/

	// Numeric keypad //////////////////////

	KEY_KP_0_R = 0xd2,
	KEY_KP_1_R = 0xcf,
	KEY_KP_2_R = 0xd0,
	KEY_KP_3_R = 0xd1,
	KEY_KP_4_R = 0xcb,
	KEY_KP_5_R = 0xcc,
	KEY_KP_6_R = 0xcd,
	KEY_KP_7_R = 0xc7,
	KEY_KP_8_R = 0xc8,
	KEY_KP_9_R = 0xc9,
	KEY_KP_PLUS_R = 0xce,
	KEY_KP_MINUS_R = 0xca,
	KEY_KP_DECIMAL_R = 0xd3,
	KEY_KP_DIVIDE_R = 0xb5,
	KEY_KP_ASTERISK_R = 0xb7,
	//KEY_KP_NUMLOCK_R = 0x77,
	KEY_KP_ENTER_R = 0x9c,

	KEY_TAB_R = 0x8f,
	//KEY_CAPSLOCK_R = 0x4001,

	// Modify keys ////////////////////////////

	KEY_LSHIFT_R = 0xaa,
	KEY_LCTRL_R = 0x9d,
	KEY_LALT_R = 0xb8,
	KEY_LWIN_R = 0xdb,
	KEY_RSHIFT_R = 0xb6,
	//KEY_RCTRL = 0x4007,
	//KEY_RALT = 0x4008,
	//KEY_RWIN = 0x4009,

	//KEY_INSERT = 0x400a,
	//KEY_DELETE = 0x400b,
	//KEY_HOME = 0x400c,
	//KEY_END = 0x400d,
	//KEY_PAGEUP = 0x400e,
	//KEY_PAGEDOWN = 0x400f,
	//KEY_SCROLLLOCK = 0x4010,
	//KEY_PAUSE = 0x4011,
} KEYCODE;
#pragma pack(pop)

#endif // _SCAN_CODES_H